[package]
name = "ch-12-toy-global"
version = "0.1.0"
authors = ["Nathan Brown <nathan@nkbrown.us>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
